apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: raviteja@tradery.io
    privateKeySecretRef:
      name: lets-encrypt-cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx