apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service-app
  template:
    metadata:
      labels:
        app: scheduler-service-app
    spec:
      containers:
        - name: scheduler-service-app
          image: 965265258350.dkr.ecr.us-east-1.amazonaws.com/scheduler-service:latest

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  type: NodePort
  selector:
    app: scheduler-service-app
  ports:
    - port: 8090
      targetPort: 8080
